services:
  - type: web
    name: crypto-assistant-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python assistant_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN_2
        sync: false
      - key: INTERNAL_BROADCAST_SECRET
        sync: false
      - key: ALLOW_REAL_BROADCAST
        value: "false"
      - key: TELEGRAM_BOT_TOKEN_1
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: CG_DEMO_API_KEY
        sync: false
    plan: free
